version: '3.8'

services:
  backend:
    container_name: backend-employee-manager-pagination
    image: bgnatowski/customer-pagination-backend:v1 # v1 - windows / v2 - macos
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: "on-failure"
  frontend:
    container_name: frontend-employee-manager-pagination
    image: bgnatowski/customer-pagination-frontend:v1 # v1 - windows / v2 - macos
    ports:
      - "4200:80"
    depends_on:
      - backend
      - db
    restart: "on-failure"
  db:
    container_name: postgres-db-employee-manager-pagination
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: employee-db
      POSTGRES_USER: bgnat
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./employee-db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db:
