services:
  db:
    container_name: postgres-db-employee-manager-pagination
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: employee-db
      POSTGRES_USER: bgnat
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./employee-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:

